#!/bin/bash
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '10' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_10.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '11' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_11.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '12' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_12.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '13' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_13.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '14' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_14.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '15' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_15.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '16' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_16.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '17' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_17.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '18' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_18.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '19' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_19.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '20' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_20.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '21' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_21.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '22' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_22.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '23' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_23.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '24' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_24.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '25' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_25.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '26' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_26.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '27' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_27.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '28' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_28.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko
mysql -N -e"select from_unixtime(timestamp), rpm_diesel, power_generator, poz_kont_sec from full_sql_locodataseconds where loco_id = '29' and poz_kont_sec is not null" > /home/mark/PycharmProjects/loko-project/lokodata_29.txt -h 'lokosampledb.cozlbgcgmptq.us-east-2.rds.amazonaws.com' -u readslave -przd_2020 dbloko



